branches:
  only:
    - master
    
addons:
  apt:
    packages:
      - build-essential
      - python

services:
  - docker

jobs:
  include:
    - stage: test
      name: "Unit Tests: Node 10"
      language: node_js
      sudo: required
      dist: xenial

      node_js:
        - "10"

      services:
        - mysql

      install:
        - npm install

      before_install:
        - sudo mysql -e "use mysql; update user set authentication_string=password('test') where user='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
        - sudo mysql_upgrade -u root -ptest
        - sudo service mysql restart

      before_script:
        - npm run lint
        - node ./test/database

      script:
        - IDM_DB_PASS=test IDM_DB_NAME=idm_test npm test

      after_script:
        - npm run test:coveralls

    - stage: test
      name: "Unit Tests: Node 12"
      language: node_js
      sudo: required
      dist: xenial

      node_js:
        - "12"

      services:
        - mysql

      install:
        - npm install

      before_install:
        - sudo mysql -e "use mysql; update user set authentication_string=password('test') where user='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
        - sudo mysql_upgrade -u root -ptest
        - sudo service mysql restart

      before_script:
        - npm run lint
        - node ./test/database

      script:
        - IDM_DB_PASS=test IDM_DB_NAME=idm_test npm test

      after_script:
        - npm run test:coveralls

    - stage: test
      name: "Documentation Tests"
      language: node_js

      node_js:
        - "10"

      install:
        - npm install

      script:
        - npm run lint:md
        - npm run lint:text

    - stage: test
      name: "Dockerfile Tests"
      language: bash
      before_script:
        - docker pull hadolint/hadolint
      script:
        - docker run --rm -i hadolint/hadolint < ./extras/docker/Dockerfile
